### ISSUE TITLE
🐛[BUG] 与Clash的兼容问题

### ISSUE THREAD

**Issue by Z-fly** [misaka10843/copymanga-download#8]
![image](https://user-images.githubusercontent.com/10470892/159108469-417dc3b0-2f5e-4e9e-8af1-895968d86497.png)
设置了系统代理，似乎requests就报错了。可能的原因：requests与Clash系统代理不兼容
![image](https://user-images.githubusercontent.com/10470892/159108489-e2212ce0-27f0-43c0-889d-246accbec3ca.png)

**Comment by Z-fly** [comment]
其他工具 如ssr v2ray未尝试 大家可以测测

**Comment by Z-fly** [comment]
之前考虑用set https_proxy=http://127.0.0.1:7890 强制走代理，但我发现系统代理会默认接管了requests？
![image](https://user-images.githubusercontent.com/10470892/159108582-bc0b3da2-5c5f-467e-8ca3-7be4a42df81e.png)

**Comment by misaka10843** [comment]
的确有小伙伴发issue说过代理问题，当时也没在意（毕竟是走路由器代理的）

然后也发现了似乎走代理会被copymanga拦截（不知道为什么）

虽然在另一个分支暂时添加了代理设置，但是因为分支主要是为了支持热辣漫画而创建的（但是因为无法获取完整图源所以并没有合并就对了www）

**Comment by Z-fly** [comment]
经过测试  ![image](https://user-images.githubusercontent.com/10470892/159286734-5beee4b8-0dfa-486a-af1a-d69561202aee.png)
set https_proxy=http://127.0.0.1:7890 还是有问题的 看来我之前想当然了
现在要解决的问题就是，要在代码里识别到有没有使用系统代理，使用的话能正确走代理 不报错

**Comment by misaka10843** [comment]
> 经过测试 ![image](https://user-images.githubusercontent.com/10470892/159286734-5beee4b8-0dfa-486a-af1a-d69561202aee.png) set https_proxy=http://127.0.0.1:7890 还是有问题的 看来我之前想当然了 现在要解决的问题就是，要在代码里识别到有没有使用系统代理，使用的话能正确走代理 不报错

如果检测系统代理的话可能不会正常工作（毕竟似乎只能查注册表www，而如路由器代理等无法解决）

但是如果是路由器代理的话也不能解决（只能关闭）

所以现在我认为还是先试一下设置requests中的proxies来替换系统代理（或者更改为自定义代理）

如果不行的话再试试其他方法吧qwq

**Comment by misaka10843** [comment]
暂时修改了一下，因为没有全局代理（只有个岛风Go）所以还没有测试qwq #9

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/159436412-b59217b8-c87d-4405-8582-f19142f5c989.png)
Traceback (most recent call last):
  File "/Users/z/Downloads/漫画/copy.py", line 285, in <module>
    manga_download()
  File "/Users/z/Downloads/漫画/copy.py", line 162, in manga_download
    response = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Z-fly** [comment]
mac下似乎可以用这个命令让代理接管 export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890

**Comment by Z-fly** [comment]
上面的错误大概是代理波动了，所以得用try去捕获重试一下

**Comment by misaka10843** [comment]
因为我用我这边的代理的话似乎查不出什么问题，所以可能无法修复这个bug（太迷了）

最好还是关闭代理后下载吧🤣

**Comment by zhongfly** [comment]
我感觉是和这个issue有关 https://github.com/psf/requests/issues/5740

**Comment by zhongfly** [comment]
> > 我感觉是和这个issue有关 [psf/requests#5740](https://github.com/psf/requests/issues/5740)
> > 具体原理可能是这个 https://note.bobo.moe/2021/02/clash-for-windows-pip-proxyerror.html
> 
> 你能否方便详细讲一下，我在好多仓库看到你，方便加个好友吗

第二个链接里说的比较清楚。
主要是https_proxy的问题：cfw设置代理是不带前缀的，只有“127.0.0.1:port"；没前缀时，urllib会自动补全，于是urllib里https_proxy就被自动设置为`https://127.0.0.1:port`，然而我们使用的代理正确的写法应该是`http://127.0.0.1:7890/`，不是https的

**Comment by zhongfly** [comment]
> > > > 我感觉是和这个issue有关 [psf/requests#5740](https://github.com/psf/requests/issues/5740)
> > > > 具体原理可能是这个 https://note.bobo.moe/2021/02/clash-for-windows-pip-proxyerror.html
> > > 
> > > 
> > > 你能否方便详细讲一下，我在好多仓库看到你，方便加个好友吗
> > 
> > 
> > 第二个链接里说的比较清楚。 主要是https_proxy的问题：cfw设置代理是不带前缀的，只有“127.0.0.1:port"；没前缀时，urllib会自动补全，于是urllib里https_proxy就被自动设置为`https://127.0.0.1:port`，然而我们使用的代理正确的写法应该是`http://127.0.0.1:7890/`，不是https的
> 
> 能否加个qq ：2 6 5 8 0 4 1 5 7 9，具体写代码的时候还要请教一下

tg吧 [@shadows0o0](https://t.me/shadows0o0) 我个人不怎么写代码的…

**Comment by misaka10843** [comment]
也就是说，出现代理问题其实是因为clash走代理的时候并没指定具体协议导致urllib直走ssl
从而出现此错误？
（如果是这样的话就可以不需要修了www）

**Comment by misaka10843** [comment]
> 

已经改了吗？（域名变换的真快）
那就在优化manga_download()的时候顺便改一下吧qwq

**Comment by zhongfly** [comment]
> 已经改了吗？（域名变换的真快） 那就在优化manga_download()的时候顺便改一下吧qwq

app上抓包是改了的，不过不改也无所谓，老域名一样能用
